data_dir: ./data/frog_2022_04_29
recording_names: 
- Xla_2022-04-29_Ph00_19
lr: 5e-4 
epochs: 80 
batch_size: 256 
steps_til_eval: 8000 
k: PoissonNet2-18ds_992in
stride: 13 
weight_decay: 0.3
pin_memory: true
num_workers: 20
steps_til_log: 20
labels: recreate_paper,frog,poisson
