#!/bin/bash
docker run -it \
--gpus all \
--ipc=host \
--name="csj-jupyter-$(date +%s)" \
-v $(pwd):/app \
-p 0.0.0.0:8888:8888 \
-p 0.0.0.0:8050:8050 \
csi \
jupyter lab --notebook-dir='./notebooks' --no-browser --ip=0.0.0.0 --port=8888 
